### PR TITLE
initial boilerplate commit

### PR DESCRIPTION
**Pull request by hshaosf**
Initial boilerplate commit

### CODE REVIEW

**Comment by hshaosf** [comment]
Its an example under the `examples` folder.  I figure I will create an example app if anyone wanna see an example. The actual boilerplate SDK is under `boilerplate_sdk`.  Sorry for the confusion.

**Comment by josh-chou** [comment]
Oh ok.  I didn't catch that.  It's also a little confusing because the boilerplate sdk is named example.py.

**Comment by hshaosf** [comment]
Yeah, definitely open to ideas on what would be a more fitting naming.

**Comment by hshaosf** [comment]
@josh-chou renamed based on what we discussed. b086126

**Pull request merged**
